import oracledb
import os
from dotenv import load_dotenv

load_dotenv()

try:
    connection = oracledb.connect(
        user=os.environ.get("ORACLE_USER", "system"),
        password=os.environ.get("ORACLE_PASSWORD", "dbms123"),
        dsn=os.environ.get("ORACLE_DSN", "localhost/XE")
    )
    cursor = connection.cursor()
    
    # Drop existing tables
    try:
        cursor.execute("DROP TABLE OTP_VERIFICATION")
        print("✓ Dropped OTP_VERIFICATION table")
    except:
        pass
    
    try:
        cursor.execute("DROP TABLE HACKATHON_STUDENTS")
        print("✓ Dropped HACKATHON_STUDENTS table")
    except:
        pass
    
    connection.commit()
    
    # Recreate with correct schema
    cursor.execute("""
        CREATE TABLE HACKATHON_STUDENTS (
            STUDENT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            STUDENT_NAME VARCHAR2(100),
            EMAIL_ID VARCHAR2(100) UNIQUE,
            PASS_WORD VARCHAR2(255),
            COLLEGE_NAME VARCHAR2(150),
            HACKATHON_PREFERENCE VARCHAR2(100),
            FRONTEND_SKILL NUMBER,
            BACKEND_SKILL NUMBER,
            COMMUNICATION_SKILL NUMBER,
            LEADERSHIP_SKILL NUMBER,
            CLUSTER_ID NUMBER,
            TEAM_ID NUMBER,
            ROLE VARCHAR2(50),
            BRANCH VARCHAR2(50),
            YEAR_OF_STUDY VARCHAR2(10),
            GITHUB_LINK VARCHAR2(255),
            LINKEDIN_LINK VARCHAR2(255),
            BIO VARCHAR2(500)
        )
    """)
    
    cursor.execute("""
        CREATE TABLE OTP_VERIFICATION (
            OTP_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            STUDENT_ID NUMBER REFERENCES HACKATHON_STUDENTS(STUDENT_ID),
            OTP VARCHAR2(6),
            EXPIRY_TIME DATE
        )
    """)
    
    connection.commit()
    print("✓ Tables recreated with PASS_WORD VARCHAR2(255)")
    connection.close()
    
except Exception as e:
    print(f"Error: {e}")
